#ifndef HTZ_GAME_SCREEN_H
#define HTZ_GAME_SCREEN_H

#define SCREEN_ASPECT_RATIO (16.0 / 9.0)

// #define SCREEN_WIDTH 1920
// #define SCREEN_HEIGHT 1080
#define SCREEN_WIDTH 1440
#define SCREEN_HEIGHT (SCREEN_WIDTH / SCREEN_ASPECT_RATIO)

#endif
